# Guest OS timezone
timezone: Europe/Moscow

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: openshift

# Virtual machine name
domain_name: oc.webegin.pro

# Virtual machine name
domain_apps: apps.webegin.pro

# Virtual machine name
domain_node: node01.webegin.pro

# Virtual machine IP
ip: 192.168.83.138

# Vagrant SSH port forwarding
#vagrant_ssh: 2222

# Virtual machine box
vm_box: bento/centos-7.3
    
# Virtual machine box url
# vm_box_url: 

# Virtual machine CPU cores number
cpus: 4

# Virtual machine RAM
memory: 16384

# Openshift version
version: v1.4.1
